version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Establece la contraseña del usuario root de MySQL
      MYSQL_DATABASE: ${DB_NAME}  # Establece el nombre de la base de datos
    container_name: ${DB_NAME}
    volumes:
      - ./mysql-db:/var/lib/mysql  # Ajusta el volumen según tus necesidades
